module.exports = {
  "AF": {"en": "Afghanistan", "numericCode": "004"},
  "AX": {"en": "ALA Aland Islands", "numericCode": "248"},
  "AL": {"en": "Albania", "numericCode": "008"},
  "DZ": {"en": "Algeria", "numericCode": "012"},
  "AS": {"en": "American Samoa", "numericCode": "016"},
  "AD": {"en": "Andorra", "numericCode": "020"},
  "AO": {"en": "Angola", "numericCode": "024"},
  "AI": {"en": "Anguilla", "numericCode": "660"},
  "AQ": {"en": "Antarctica", "numericCode": "010"},
  "AG": {"en": "Antigua and Barbuda", "numericCode": "028"},
  "AR": {"en": "Argentina", "numericCode": "032"},
  "AM": {"en": "Armenia", "numericCode": "051"},
  "AW": {"en": "Aruba", "numericCode": "533"},
  "AU": {"en": "Australia", "numericCode": "036"},
  "AT": {"en": "Austria", "numericCode": "040"},
  "AZ": {"en": "Azerbaijan", "numericCode": "031"},
  "BS": {"en": "Bahamas", "numericCode": "044"},
  "BH": {"en": "Bahrain", "numericCode": "048"},
  "BD": {"en": "Bangladesh", "numericCode": "050"},
  "BB": {"en": "Barbados", "numericCode": "052"},
  "BY": {"en": "Belarus", "numericCode": "112"},
  "BE": {"en": "Belgium", "numericCode": "056"},
  "BZ": {"en": "Belize", "numericCode": "084"},
  "BJ": {"en": "Benin", "numericCode": "204"},
  "BM": {"en": "Bermuda", "numericCode": "060"},
  "BT": {"en": "Bhutan", "numericCode": "064"},
  "BO": {"en": "Bolivia", "numericCode": "068"},
  "BQ": {"en": "Caribbean Netherlands", "numericCode": "599"},
  "BA": {"en": "Bosnia and Herzegovina", "numericCode": "070"},
  "BW": {"en": "Botswana", "numericCode": "072"},
  "BV": {"en": "Bouvet Island", "numericCode": "074"},
  "BR": {"en": "Brazil", "numericCode": "076"},
  "VG": {"en": "British Virgin Islands", "numericCode": "092"},
  "IO": {"en": "British Indian Ocean Territory", "numericCode": "086"},
  "BN": {"en": "Brunei Darussalam", "numericCode": "096"},
  "BG": {"en": "Bulgaria", "numericCode": "100"},
  "BF": {"en": "Burkina Faso", "numericCode": "854"},
  "BI": {"en": "Burundi", "numericCode": "108"},
  "KH": {"en": "Cambodia", "numericCode": "116"},
  "CM": {"en": "Cameroon", "numericCode": "120"},
  "CA": {"en": "Canada", "numericCode": "124"},
  "CV": {"en": "Cape Verde", "numericCode": "132"},
  "KY": {"en": "Cayman Islands", "numericCode": "136"},
  "CF": {"en": "Central African Republic", "numericCode": "140"},
  "TD": {"en": "Chad", "numericCode": "148"},
  "CL": {"en": "Chile", "numericCode": "152"},
  "CN": {"en": "China", "numericCode": "156"},
  "HK": {"en": "Hong Kong, SAR China", "numericCode": "344"},
  "MO": {"en": "Macao, SAR China", "numericCode": "446"},
  "CX": {"en": "Christmas Island", "numericCode": "162"},
  "CC": {"en": "Cocos (Keeling) Islands", "numericCode": "166"},
  "CO": {"en": "Colombia", "numericCode": "170"},
  "KM": {"en": "Comoros", "numericCode": "174"},
  "CG": {"en": "Congo (Brazzaville)", "numericCode": "178"},
  "CD": {"en": "Congo, (Kinshasa)", "numericCode": "180"},
  "CK": {"en": "Cook Islands", "numericCode": "184"},
  "CR": {"en": "Costa Rica", "numericCode": "188"},
  "CI": {"en": "Côte d'Ivoire", "numericCode": "384"},
  "HR": {"en": "Croatia", "numericCode": "191"},
  "CU": {"en": "Cuba", "numericCode": "192"},
  "CY": {"en": "Cyprus", "numericCode": "196"},
  "CZ": {"en": "Czech Republic", "numericCode": "203"},
  "DK": {"en": "Denmark", "numericCode": "208"},
  "DJ": {"en": "Djibouti", "numericCode": "262"},
  "DM": {"en": "Dominica", "numericCode": "212"},
  "DO": {"en": "Dominican Republic", "numericCode": "214"},
  "EC": {"en": "Ecuador", "numericCode": "218"},
  "EG": {"en": "Egypt", "numericCode": "818"},
  "SV": {"en": "El Salvador", "numericCode": "222"},
  "GQ": {"en": "Equatorial Guinea", "numericCode": "226"},
  "ER": {"en": "Eritrea", "numericCode": "232"},
  "EE": {"en": "Estonia", "numericCode": "233"},
  "ET": {"en": "Ethiopia", "numericCode": "231"},
  "FK": {"en": "Falkland Islands (Malvina)", "numericCode": "238"},
  "FO": {"en": "Faroe Islands", "numericCode": "234"},
  "FJ": {"en": "Fiji", "numericCode": "242"},
  "FI": {"en": "Finland", "numericCode": "246"},
  "FR": {"en": "France", "numericCode": "250"},
  "GF": {"en": "French Guiana", "numericCode": "254"},
  "PF": {"en": "French Polynesia", "numericCode": "258"},
  "TF": {"en": "French Southern Territories", "numericCode": "260"},
  "GA": {"en": "Gabon", "numericCode": "266"},
  "GM": {"en": "Gambia", "numericCode": "270"},
  "GE": {"en": "Georgia", "numericCode": "268"},
  "DE": {"en": "Germany", "numericCode": "276"},
  "GH": {"en": "Ghana", "numericCode": "288"},
  "GI": {"en": "Gibraltar", "numericCode": "292"},
  "GR": {"en": "Greece", "numericCode": "300"},
  "GL": {"en": "Greenland", "numericCode": "304"},
  "GD": {"en": "Grenada", "numericCode": "308"},
  "GP": {"en": "Guadeloupe", "numericCode": "312"},
  "GU": {"en": "Guam", "numericCode": "316"},
  "GT": {"en": "Guatemala", "numericCode": "320"},
  "GG": {"en": "Guernsey", "numericCode": "831"},
  "GN": {"en": "Guinea", "numericCode": "324"},
  "GW": {"en": "Guinea-Bissau", "numericCode": "624"},
  "GY": {"en": "Guyana", "numericCode": "328"},
  "HT": {"en": "Haiti", "numericCode": "332"},
  "HM": {"en": "Heard and Mcdonald Islands", "numericCode": "334"},
  "VA": {"en": "Holy See (Vatican City State)", "numericCode": "336"},
  "HN": {"en": "Honduras", "numericCode": "340"},
  "HU": {"en": "Hungary", "numericCode": "348"},
  "IS": {"en": "Iceland", "numericCode": "352"},
  "IN": {"en": "India", "numericCode": "356"},
  "ID": {"en": "Indonesia", "numericCode": "360"},
  "IR": {"en": "Iran, Islamic Republic of", "numericCode": "364"},
  "IQ": {"en": "Iraq", "numericCode": "368"},
  "IE": {"en": "Ireland", "numericCode": "372"},
  "IM": {"en": "Isle of Man", "numericCode": "833"},
  "IL": {"en": "Israel", "numericCode": "376"},
  "IT": {"en": "Italy", "numericCode": "380"},
  "JM": {"en": "Jamaica", "numericCode": "388"},
  "JP": {"en": "Japan", "numericCode": "392"},
  "JE": {"en": "Jersey", "numericCode": "832"},
  "JO": {"en": "Jordan", "numericCode": "400"},
  "KZ": {"en": "Kazakhstan", "numericCode": "398"},
  "KE": {"en": "Kenya", "numericCode": "404"},
  "KI": {"en": "Kiribati", "numericCode": "296"},
  "KP": {"en": "Korea (North)", "numericCode": "408"},
  "KR": {"en": "Korea (South)", "numericCode": "410"},
  "KW": {"en": "Kuwait", "numericCode": "414"},
  "KG": {"en": "Kyrgyzstan", "numericCode": "417"},
  "LA": {"en": "Lao PDR", "numericCode": "418"},
  "LV": {"en": "Latvia", "numericCode": "428"},
  "LB": {"en": "Lebanon", "numericCode": "422"},
  "LS": {"en": "Lesotho", "numericCode": "426"},
  "LR": {"en": "Liberia", "numericCode": "430"},
  "LY": {"en": "Libya", "numericCode": "434"},
  "LI": {"en": "Liechtenstein", "numericCode": "438"},
  "LT": {"en": "Lithuania", "numericCode": "440"},
  "LU": {"en": "Luxembourg", "numericCode": "442"},
  "MK": {"en": "Macedonia, Republic of", "numericCode": "807"},
  "MG": {"en": "Madagascar", "numericCode": "450"},
  "MW": {"en": "Malawi", "numericCode": "454"},
  "MY": {"en": "Malaysia", "numericCode": "458"},
  "MV": {"en": "Maldives", "numericCode": "462"},
  "ML": {"en": "Mali", "numericCode": "466"},
  "MT": {"en": "Malta", "numericCode": "470"},
  "MH": {"en": "Marshall Islands", "numericCode": "584"},
  "MQ": {"en": "Martinique", "numericCode": "474"},
  "MR": {"en": "Mauritania", "numericCode": "478"},
  "MU": {"en": "Mauritius", "numericCode": "480"},
  "YT": {"en": "Mayotte", "numericCode": "175"},
  "MX": {"en": "Mexico", "numericCode": "484"},
  "FM": {"en": "Micronesia, Federated States of", "numericCode": "583"},
  "MD": {"en": "Moldova", "numericCode": "498"},
  "MC": {"en": "Monaco", "numericCode": "492"},
  "MN": {"en": "Mongolia", "numericCode": "496"},
  "ME": {"en": "Montenegro", "numericCode": "499"},
  "MS": {"en": "Montserrat", "numericCode": "500"},
  "MA": {"en": "Morocco", "numericCode": "504"},
  "MZ": {"en": "Mozambique", "numericCode": "508"},
  "MM": {"en": "Myanmar", "numericCode": "104"},
  "NA": {"en": "Namibia", "numericCode": "516"},
  "NR": {"en": "Nauru", "numericCode": "520"},
  "NP": {"en": "Nepal", "numericCode": "524"},
  "NL": {"en": "Netherlands", "numericCode": "528"},
  "AN": {"en": "Netherlands Antilles", "numericCode": "530"},
  "NC": {"en": "New Caledonia", "numericCode": "540"},
  "NZ": {"en": "New Zealand", "numericCode": "554"},
  "NI": {"en": "Nicaragua", "numericCode": "558"},
  "NE": {"en": "Niger", "numericCode": "562"},
  "NG": {"en": "Nigeria", "numericCode": "566"},
  "NU": {"en": "Niue", "numericCode": "570"},
  "NF": {"en": "Norfolk Island", "numericCode": "574"},
  "MP": {"en": "Northern Mariana Islands", "numericCode": "580"},
  "NO": {"en": "Norway", "numericCode": "578"},
  "OM": {"en": "Oman", "numericCode": "512"},
  "PK": {"en": "Pakistan", "numericCode": "586"},
  "PW": {"en": "Palau", "numericCode": "585"},
  "PS": {"en": "Palestinian Territory", "numericCode": "275"},
  "PA": {"en": "Panama", "numericCode": "591"},
  "PG": {"en": "Papua New Guinea", "numericCode": "598"},
  "PY": {"en": "Paraguay", "numericCode": "600"},
  "PE": {"en": "Peru", "numericCode": "604"},
  "PH": {"en": "Philippines", "numericCode": "608"},
  "PN": {"en": "Pitcairn", "numericCode": "612"},
  "PL": {"en": "Poland", "numericCode": "616"},
  "PT": {"en": "Portugal", "numericCode": "620"},
  "PR": {"en": "Puerto Rico", "numericCode": "630"},
  "QA": {"en": "Qatar", "numericCode": "634"},
  "RE": {"en": "Réunion", "numericCode": "638"},
  "RO": {"en": "Romania", "numericCode": "642"},
  "RU": {"en": "Russian Federation", "numericCode": "643"},
  "RW": {"en": "Rwanda", "numericCode": "646"},
  "BL": {"en": "Saint-Barthélemy", "numericCode": "652"},
  "SH": {"en": "Saint Helena", "numericCode": "654"},
  "KN": {"en": "Saint Kitts and Nevis", "numericCode": "659"},
  "LC": {"en": "Saint Lucia", "numericCode": "662"},
  "MF": {"en": "Saint-Martin (French part)",  "numericCode": "663"},
  "PM": {"en": "Saint Pierre and Miquelon", "numericCode": "666"},
  "VC": {"en": "Saint Vincent and Grenadines", "numericCode": "670"},
  "WS": {"en": "Samoa", "numericCode": "882"},
  "SM": {"en": "San Marino", "numericCode": "674"},
  "ST": {"en": "Sao Tome and Principe", "numericCode": "678"},
  "SA": {"en": "Saudi Arabia", "numericCode": "682"},
  "SN": {"en": "Senegal", "numericCode": "686"},
  "RS": {"en": "Serbia", "numericCode": "688"},
  "SC": {"en": "Seychelles", "numericCode": "690"},
  "SL": {"en": "Sierra Leone", "numericCode": "694"},
  "SG": {"en": "Singapore", "numericCode": "702"},
  "SK": {"en": "Slovakia", "numericCode": "703"},
  "SI": {"en": "Slovenia", "numericCode": "705"},
  "SB": {"en": "Solomon Islands", "numericCode": "090"},
  "SO": {"en": "Somalia", "numericCode": "706"},
  "ZA": {"en": "South Africa", "numericCode": "710"},
  "GS": {"en": "South Georgia and the South Sandwich Islands", "numericCode": "239"},
  "SS": {"en": "South Sudan", "numericCode": "728"},
  "ES": {"en": "Spain", "numericCode": "724"},
  "LK": {"en": "Sri Lanka", "numericCode": "144"},
  "SD": {"en": "Sudan", "numericCode": "736"},
  "SR": {"en": "Suriname", "numericCode": "740"},
  "SJ": {"en": "Svalbard and Jan Mayen Islands", "numericCode": "744"},
  "SZ": {"en": "Swaziland", "numericCode": "748"},
  "SE": {"en": "Sweden", "numericCode": "752"},
  "CH": {"en": "Switzerland", "numericCode": "756"},
  "SY": {"en": "Syrian Arab Republic (Syria)", "numericCode": "760"},
  "TW": {"en": "Taiwan, Republic of China", "numericCode": "158"},
  "TJ": {"en": "Tajikistan", "numericCode": "762"},
  "TZ": {"en": "Tanzania, United Republic of", "numericCode": "834"},
  "TH": {"en": "Thailand", "numericCode": "764"},
  "TL": {"en": "Timor-Leste", "numericCode": "626"},
  "TG": {"en": "Togo", "numericCode": "768"},
  "TK": {"en": "Tokelau", "numericCode": "772"},
  "TO": {"en": "Tonga", "numericCode": "776"},
  "TT": {"en": "Trinidad and Tobago", "numericCode": "780"},
  "TN": {"en": "Tunisia", "numericCode": "788"},
  "TR": {"en": "Turkey", "numericCode": "792"},
  "TM": {"en": "Turkmenistan", "numericCode": "795"},
  "TC": {"en": "Turks and Caicos Islands", "numericCode": "796"},
  "TV": {"en": "Tuvalu", "numericCode": "798"},
  "UG": {"en": "Uganda", "numericCode": "800"},
  "UA": {"en": "Ukraine", "numericCode": "804"},
  "AE": {"en": "United Arab Emirates", "numericCode": "784"},
  "GB": {"en": "United Kingdom", "numericCode": "826"},
  "US": {"en": "United States of America", "numericCode": "840"},
  "UM": {"en": "US Minor Outlying Islands", "numericCode": "581"},
  "UY": {"en": "Uruguay", "numericCode": "858"},
  "UZ": {"en": "Uzbekistan", "numericCode": "860"},
  "VU": {"en": "Vanuatu", "numericCode": "548"},
  "VE": {"en": "Venezuela (Bolivarian Republic)", "numericCode": "862"},
  "VN": {"en": "Viet Nam", "numericCode": "704"},
  "VI": {"en": "Virgin Islands, US", "numericCode": "850"},
  "WF": {"en": "Wallis and Futuna Islands", "numericCode": "876"},
  "EH": {"en": "Western Sahara", "numericCode": "732"},
  "XK": {"en": "Kosovo", "numericCode": "383"},
  "YE": {"en": "Yemen", "numericCode": "887"},
  "ZM": {"en": "Zambia", "numericCode": "894"},
  "ZW": {"en": "Zimbabwe", "numericCode": "716"},
  "--": {"en": "--", "numericCode": "---"},
}