module.exports = {
  "AX": { en: 'Aaland Islands', numericCode: 248},
  "AF": { en: 'Afghanistan', numericCode: 4},
  "AL": { en: 'Albania', numericCode: 8},
  "DZ": { en: 'Algeria', numericCode: 12},
  "AS": { en: 'American Samoa', numericCode: 16},
  "AD": { en: 'Andorra', numericCode: 20},
  "AO": { en: 'Angola', numericCode: 24},
  "AI": { en: 'Anguilla', numericCode: 660},
  "AQ": { en: 'Antarctica', numericCode: 10},
  "AG": { en: 'Antigua and Barbuda', numericCode: 28},
  "AR": { en: 'Argentina', numericCode: 32},
  "AM": { en: 'Armenia', numericCode: 51},
  "AW": { en: 'Aruba', numericCode: 533},
  "AU": { en: 'Australia', numericCode: 36},
  "AT": { en: 'Austria', numericCode: 40},
  "AZ": { en: 'Azerbaijan', numericCode: 31},
  "BS": { en: 'Bahamas', numericCode: 44},
  "BH": { en: 'Bahrain', numericCode: 48},
  "BD": { en: 'Bangladesh', numericCode: 50},
  "BB": { en: 'Barbados', numericCode: 52},
  "BY": { en: 'Belarus', numericCode: 112},
  "BE": { en: 'Belgium', numericCode: 56},
  "BZ": { en: 'Belize', numericCode: 84},
  "BJ": { en: 'Benin', numericCode: 204},
  "BM": { en: 'Bermuda', numericCode: 60},
  "BT": { en: 'Bhutan', numericCode: 64},
  "BO": { en: 'Bolivia', numericCode: 68},
  "BA": { en: 'Bosnia and Herzegowina', numericCode: 70},
  "BW": { en: 'Botswana', numericCode: 72},
  "BV": { en: 'Bouvet Island', numericCode: 74},
  "BR": { en: 'Brazil', numericCode: 76},
  "IO": { en: 'British Indian Ocean Territory', numericCode: 86},
  "BN": { en: 'Brunei Darussalam', numericCode: 96},
  "BG": { en: 'Bulgaria', numericCode: 100},
  "BF": { en: 'Burkina Faso', numericCode: 854},
  "BI": { en: 'Burundi', numericCode: 108},
  "KH": { en: 'Cambodia', numericCode: 116},
  "CM": { en: 'Cameroon', numericCode: 120},
  "CA": { en: 'Canada', numericCode: 124},
  "CV": { en: 'Cape Verde', numericCode: 132},
  "KY": { en: 'Cayman Islands', numericCode: 136},
  "CF": { en: 'Central African Republic', numericCode: 140},
  "TD": { en: 'Chad', numericCode: 148},
  "CL": { en: 'Chile', numericCode: 152},
  "CN": { en: 'China', numericCode: 156},
  "CX": { en: 'Christmas Island', numericCode: 162},
  "CC": { en: 'Cocos (keeling) Islands', numericCode: 166},
  "CO": { en: 'Colombia', numericCode: 170},
  "KM": { en: 'Comoros', numericCode: 174},
  "CD": { en: 'Democratic Republic of Congo', numericCode: 180},
  "CG": { en: 'Republoc of Congo', numericCode: 178},
  "CK": { en: 'Cook Islands', numericCode: 184},
  "CR": { en: 'Costa Rica', numericCode: 188},
  "CI": { en: 'Cote D\'ivoire', numericCode: 384},
  "HR": { en: 'Croatia (local Name: Hrvatska)', numericCode: 191    },
  "CU": { en: 'Cuba', numericCode: 192},
  "CY": { en: 'Cyprus', numericCode: 196},
  "CZ": { en: 'Czech Republic', numericCode: 203},
  "DK": { en: 'Denmark', numericCode: 208},
  "DJ": { en: 'Djibouti', numericCode: 262},
  "DM": { en: 'Dominica', numericCode: 212},
  "DO": { en: 'Dominican Republic', numericCode: 214},
  "EC": { en: 'Ecuador', numericCode: 218},
  "EG": { en: 'Egypt', numericCode: 818},
  "SV": { en: 'El Salvador', numericCode: 222},
  "GQ": { en: 'Equatorial Guinea', numericCode: 226},
  "ER": { en: 'Eritrea', numericCode: 232},
  "EE": { en: 'Estonia', numericCode: 233},
  "ET": { en: 'Ethiopia', numericCode: 231},
  "FK": { en: 'Falkland Islands (malvinas)', numericCode: 238},
  "FO": { en: 'Faroe Islands', numericCode: 234},
  "FJ": { en: 'Fiji', numericCode: 242},
  "FI": { en: 'Finland', numericCode: 246},
  "FR": { en: 'France', numericCode: 250},
  "GF": { en: 'French Guiana', numericCode: 254},
  "PF": { en: 'French Polynesia', numericCode: 258},
  "TF": { en: 'French Southern Territories', numericCode: 260},
  "GA": { en: 'Gabon', numericCode: 266},
  "GM": { en: 'Gambia', numericCode: 270},
  "GE": { en: 'Georgia', numericCode: 268},
  "DE": { en: 'Germany', numericCode: 276},
  "GH": { en: 'Ghana', numericCode: 288},
  "GI": { en: 'Gibraltar', numericCode: 292},
  "GR": { en: 'Greece', numericCode: 300},
  "GL": { en: 'Greenland', numericCode: 304},
  "GD": { en: 'Grenada', numericCode: 308},
  "GP": { en: 'Guadeloupe', numericCode: 312},
  "GU": { en: 'Guam', numericCode: 316},
  "GT": { en: 'Guatemala', numericCode: 320},
  "GN": { en: 'Guinea', numericCode: 324},
  "GW": { en: 'Guinea-bissau', numericCode: 624},
  "GY": { en: 'Guyana', numericCode: 328},
  "HT": { en: 'Haiti', numericCode: 332},
  "HM": { en: 'Heard and Mc Donald Islands', numericCode: 334},
  "HN": { en: 'Honduras', numericCode: 340},
  "HK": { en: 'Hong Kong', numericCode: 344},
  "HU": { en: 'Hungary', numericCode: 348},
  "IS": { en: 'Iceland', numericCode: 352},
  "IN": { en: 'India', numericCode: 356},
  "ID": { en: 'Indonesia', numericCode: 360},
  "IR": { en: 'Iran (islamic Republic of)', numericCode: 364},
  "IQ": { en: 'Iraq', numericCode: 368},
  "IE": { en: 'Ireland', numericCode: 372},
  "IL": { en: 'Israel', numericCode: 376},
  "IT": { en: 'Italy', numericCode: 380},
  "JM": { en: 'Jamaica', numericCode: 388},
  "JP": { en: 'Japan', numericCode: 392},
  "JO": { en: 'Jordan', numericCode: 400},
  "KZ": { en: 'Kazakhstan', numericCode: 398},
  "KE": { en: 'Kenya', numericCode: 404},
  "KI": { en: 'Kiribati', numericCode: 296},
  "KP": { en: 'Korea, Democratic People\'s Republic of', numericCode: 408},
  "KR": { en: 'Korea, Republic of', numericCode: 410},
  "KW": { en: 'Kuwait', numericCode: 414},
  "KG": { en: 'Kyrgyzstan', numericCode: 417},
  "LA": { en: 'Lao People\'s Democratic Republic', numericCode: 418},
  "LV": { en: 'Latvia', numericCode: 428},
  "LB": { en: 'Lebanon', numericCode: 422},
  "LS": { en: 'Lesotho', numericCode: 426},
  "LR": { en: 'Liberia', numericCode: 430},
  "LY": { en: 'Libyan Arab Jamahiriya', numericCode: 434},
  "LI": { en: 'Liechtenstein', numericCode: 438},
  "LT": { en: 'Lithuania', numericCode: 440},
  "LU": { en: 'Luxembourg', numericCode: 442},
  "MO": { en: 'Macau', numericCode: 446},
  "MK": { en: 'Macedonia, The Former Yugoslav Republic of', numericCode: 807 },
  "MG": { en: 'Madagascar', numericCode: 450},
  "MW": { en: 'Malawi', numericCode: 454},
  "MY": { en: 'Malaysia', numericCode: 458},
  "MV": { en: 'Maldives', numericCode: 462},
  "ML": { en: 'Mali', numericCode: 466},
  "MT": { en: 'Malta', numericCode: 470},
  "MH": { en: 'Marshall Islands', numericCode: 584},
  "MQ": { en: 'Martinique', numericCode: 474},
  "MR": { en: 'Mauritania', numericCode: 478},
  "MU": { en: 'Mauritius', numericCode: 480},
  "YT": { en: 'Mayotte', numericCode: 175},
  "MX": { en: 'Mexico', numericCode: 484},
  "FM": { en: 'Micronesia, Federated States of', numericCode: 583},
  "MD": { en: 'Moldova, Republic of', numericCode: 498},
  "MC": { en: 'Monaco', numericCode: 492},
  "MN": { en: 'Mongolia', numericCode: 496},
  "MS": { en: 'Montserrat', numericCode: 500},
  "MA": { en: 'Morocco', numericCode: 504},
  "MZ": { en: 'Mozambique', numericCode: 508},
  "MM": { en: 'Myanmar', numericCode: 104},
  "NA": { en: 'Namibia', numericCode: 516},
  "NR": { en: 'Nauru', numericCode: 520},
  "NP": { en: 'Nepal', numericCode: 524},
  "NL": { en: 'Netherlands', numericCode: 528},
  "AN": { en: 'Netherlands Antilles', numericCode: 530},
  "NC": { en: 'New Caledonia', numericCode: 540},
  "NZ": { en: 'New Zealand', numericCode: 554},
  "NI": { en: 'Nicaragua', numericCode: 558},
  "NE": { en: 'Niger', numericCode: 562},
  "NG": { en: 'Nigeria', numericCode: 566},
  "NU": { en: 'Niue', numericCode: 570},
  "NF": { en: 'Norfolk Island', numericCode: 574},
  "MP": { en: 'Northern Mariana Islands', numericCode: 580},
  "NO": { en: 'Norway', numericCode: 578},
  "OM": { en: 'Oman', numericCode: 512},
  "PK": { en: 'Pakistan', numericCode: 586},
  "PW": { en: 'Palau', numericCode: 585},
  "PS": { en: 'Palestinian Territory, Occupied', numericCode: 275},
  "PA": { en: 'Panama', numericCode: 591},
  "PG": { en: 'Papua New Guinea', numericCode: 598},
  "PY": { en: 'Paraguay', numericCode: 600},
  "PE": { en: 'Peru', numericCode: 604},
  "PH": { en: 'Philippines', numericCode: 608},
  "PN": { en: 'Pitcairn', numericCode: 612},
  "PL": { en: 'Poland', numericCode: 616},
  "PT": { en: 'Portugal', numericCode: 620},
  "PR": { en: 'Puerto Rico', numericCode: 630},
  "QA": { en: 'Qatar', numericCode: 634},
  "RE": { en: 'Reunion', numericCode: 638},
  "RO": { en: 'Romania', numericCode: 642},
  "RU": { en: 'Russian Federation', numericCode: 643},
  "RW": { en: 'Rwanda', numericCode: 646},
  "SH": { en: 'Saint Helena', numericCode: 654},
  "KN": { en: 'Saint Kitts and Nevis', numericCode: 659},
  "LC": { en: 'Saint Lucia', numericCode: 662},
  "PM": { en: 'Saint Pierre and Miquelon', numericCode: 666},
  "VC": { en: 'Saint Vincent and The Grenadines', numericCode: 670},
  "WS": { en: 'Samoa', numericCode: 882},
  "SM": { en: 'San Marino', numericCode: 674},
  "ST": { en: 'Sao Tome and Principe', numericCode: 678},
  "SA": { en: 'Saudi Arabia', numericCode: 682},
  "SN": { en: 'Senegal', numericCode: 686},
  "CS": { en: 'Serbia and Montenegro', numericCode: 891},
  "SC": { en: 'Seychelles', numericCode: 690},
  "SL": { en: 'Sierra Leone', numericCode: 694},
  "SG": { en: 'Singapore', numericCode: 702},
  "SK": { en: 'Slovakia', numericCode: 703},
  "SI": { en: 'Slovenia', numericCode: 705},
  "SB": { en: 'Solomon Islands', numericCode: 90},
  "SO": { en: 'Somalia', numericCode: 706},
  "ZA": { en: 'South Africa', numericCode: 710},
  "GS": { en: 'South Georgia and The South Sandwich Islands', numericCode: 239},
  "ES": { en: 'Spain', numericCode: 724},
  "LK": { en: 'Sri Lanka', numericCode: 144},
  "SD": { en: 'Sudan', numericCode: 736},
  "SR": { en: 'Suriname', numericCode: 740},
  "SJ": { en: 'Svalbard and Jan Mayen Islands', numericCode: 744},
  "SZ": { en: 'Swaziland', numericCode: 748},
  "SE": { en: 'Sweden', numericCode: 752},
  "CH": { en: 'Switzerland', numericCode: 756},
  "SY": { en: 'Syrian Arab Republic', numericCode: 760},
  "TW": { en: 'Taiwan', numericCode: 158},
  "TJ": { en: 'Tajikistan', numericCode: 762},
  "TZ": { en: 'Tanzania, United Republic of', numericCode: 834},
  "TH": { en: 'Thailand', numericCode: 764},
  "TL": { en: 'Timor-leste', numericCode: 626},
  "TG": { en: 'Togo', numericCode: 768},
  "TK": { en: 'Tokelau', numericCode: 772},
  "TO": { en: 'Tonga', numericCode: 776},
  "TT": { en: 'Trinidad and Tobago', numericCode: 780},
  "TN": { en: 'Tunisia', numericCode: 788},
  "TR": { en: 'Turkey', numericCode: 792},
  "TM": { en: 'Turkmenistan', numericCode: 795},
  "TC": { en: 'Turks and Caicos Islands', numericCode: 796},
  "TV": { en: 'Tuvalu', numericCode: 798},
  "UG": { en: 'Uganda', numericCode: 800},
  "UA": { en: 'Ukraine', numericCode: 804},
  "AE": { en: 'United Arab Emirates', numericCode: 784},
  "GB": { en: 'United Kingdom', numericCode: 826},
  "US": { en: 'United States', numericCode: 840},
  "UM": { en: 'United States Minor Outlying Islands', numericCode: 581},
  "UY": { en: 'Uruguay', numericCode: 858},
  "UZ": { en: 'Uzbekistan', numericCode: 860},
  "VU": { en: 'Vanuatu', numericCode: 548},
  "VA": { en: 'Vatican City State (holy See)', numericCode: 336},
  "VE": { en: 'Venezuela', numericCode: 862},
  "VN": { en: 'Viet Nam', numericCode: 704},
  "VG": { en: 'Virgin Islands (british)', numericCode: 92},
  "VI": { en: 'Virgin Islands (u.s.)', numericCode: 850},
  "WF": { en: 'Wallis and Futuna Islands', numericCode: 876},
  "EH": { en: 'Western Sahara', numericCode: 732},
  "YE": { en: 'Yemen', numericCode: 887},
  "ZM": { en: 'Zambia', numericCode: 894},
  "ZW": { en: 'Zimbabwe', numericCode: 716}
}

module.exports = {
  "AX": "Aaland Islands",
  "AF": "Afghanistan",
  "AL": "Albania",
  "DZ": "Algeria",
  "AS": "American Samoa",
  "AD": "Andorra",
  "AO": "Angola",
  "AI": "Anguilla",
  "AQ": "Antarctica",
  "AG": "Antigua and Barbuda",
  "AR": "Argentina",
  "AM": "Armenia",
  "AW": "Aruba",
  "AU": "Australia",
  "AT": "Austria",
  "AZ": "Azerbaijan",
  "BS": "Bahamas",
  "BH": "Bahrain",
  "BD": "Bangladesh",
  "BB": "Barbados",
  "BY": "Belarus",
  "BE": "Belgium",
  "BZ": "Belize",
  "BJ": "Benin",
  "BM": "Bermuda",
  "BT": "Bhutan",
  "BO": "Bolivia",
  "BA": "Bosnia and Herzegowina",
  "BW": "Botswana",
  "BV": "Bouvet Island",
  "BR": "Brazil",
  "IO": "British Indian Ocean Territory",
  "BN": "Brunei Darussalam",
  "BG": "Bulgaria",
  "BF": "Burkina Faso",
  "BI": "Burundi",
  "KH": "Cambodia",
  "CM": "Cameroon",
  "CA": "Canada",
  "CV": "Cape Verde",
  "KY": "Cayman Islands",
  "CF": "Central African Republic",
  "TD": "Chad",
  "CL": "Chile",
  "CN": "China",
  "CX": "Christmas Island",
  "CC": "Cocos (keeling) Islands",
  "CO": "Colombia",
  "KM": "Comoros",
  "CD": "Democratic Republic of Congo",
  "CG": "Republoc of Congo",
  "CK": "Cook Islands",
  "CR": "Costa Rica",
  "CI": "Cote D'ivoire",
  "HR": "Croatia (local Name: Hrvatska)",
  "CU": "Cuba",
  "CY": "Cyprus",
  "CZ": "Czech Republic",
  "DK": "Denmark",
  "DJ": "Djibouti",
  "DM": "Dominica",
  "DO": "Dominican Republic",
  "EC": "Ecuador",
  "EG": "Egypt",
  "SV": "El Salvador",
  "GQ": "Equatorial Guinea",
  "ER": "Eritrea",
  "EE": "Estonia",
  "ET": "Ethiopia",
  "FK": "Falkland Islands (malvinas)",
  "FO": "Faroe Islands",
  "FJ": "Fiji",
  "FI": "Finland",
  "FR": "France",
  "GF": "French Guiana",
  "PF": "French Polynesia",
  "TF": "French Southern Territories",
  "GA": "Gabon",
  "GM": "Gambia",
  "GE": "Georgia",
  "DE": "Germany",
  "GH": "Ghana",
  "GI": "Gibraltar",
  "GR": "Greece",
  "GL": "Greenland",
  "GD": "Grenada",
  "GP": "Guadeloupe",
  "GU": "Guam",
  "GT": "Guatemala",
  "GN": "Guinea",
  "GW": "Guinea-bissau",
  "GY": "Guyana",
  "HT": "Haiti",
  "HM": "Heard and Mc Donald Islands",
  "HN": "Honduras",
  "HK": "Hong Kong",
  "HU": "Hungary",
  "IS": "Iceland",
  "IN": "India",
  "ID": "Indonesia",
  "IR": "Iran (islamic Republic of)",
  "IQ": "Iraq",
  "IE": "Ireland",
  "IL": "Israel",
  "IT": "Italy",
  "JM": "Jamaica",
  "JP": "Japan",
  "JO": "Jordan",
  "KZ": "Kazakhstan",
  "KE": "Kenya",
  "KI": "Kiribati",
  "KP": "Korea, Democratic People's Republic of",
  "KR": "Korea, Republic of",
  "KW": "Kuwait",
  "KG": "Kyrgyzstan",
  "LA": "Lao People's Democratic Republic",
  "LV": "Latvia",
  "LB": "Lebanon",
  "LS": "Lesotho",
  "LR": "Liberia",
  "LY": "Libyan Arab Jamahiriya",
  "LI": "Liechtenstein",
  "LT": "Lithuania",
  "LU": "Luxembourg",
  "MO": "Macau",
  "MK": "Macedonia, The Former Yugoslav Republic of",
  "MG": "Madagascar",
  "MW": "Malawi",
  "MY": "Malaysia",
  "MV": "Maldives",
  "ML": "Mali",
  "MT": "Malta",
  "MH": "Marshall Islands",
  "MQ": "Martinique",
  "MR": "Mauritania",
  "MU": "Mauritius",
  "YT": "Mayotte",
  "MX": "Mexico",
  "FM": "Micronesia, Federated States of",
  "MD": "Moldova, Republic of",
  "MC": "Monaco",
  "MN": "Mongolia",
  "MS": "Montserrat",
  "MA": "Morocco",
  "MZ": "Mozambique",
  "MM": "Myanmar",
  "NA": "Namibia",
  "NR": "Nauru",
  "NP": "Nepal",
  "NL": "Netherlands",
  "AN": "Netherlands Antilles",
  "NC": "New Caledonia",
  "NZ": "New Zealand",
  "NI": "Nicaragua",
  "NE": "Niger",
  "NG": "Nigeria",
  "NU": "Niue",
  "NF": "Norfolk Island",
  "MP": "Northern Mariana Islands",
  "NO": "Norway",
  "OM": "Oman",
  "PK": "Pakistan",
  "PW": "Palau",
  "PS": "Palestinian Territory, Occupied",
  "PA": "Panama",
  "PG": "Papua New Guinea",
  "PY": "Paraguay",
  "PE": "Peru",
  "PH": "Philippines",
  "PN": "Pitcairn",
  "PL": "Poland",
  "PT": "Portugal",
  "PR": "Puerto Rico",
  "QA": "Qatar",
  "RE": "Reunion",
  "RO": "Romania",
  "RU": "Russian Federation",
  "RW": "Rwanda",
  "SH": "Saint Helena",
  "KN": "Saint Kitts and Nevis",
  "LC": "Saint Lucia",
  "PM": "Saint Pierre and Miquelon",
  "VC": "Saint Vincent and The Grenadines",
  "WS": "Samoa",
  "SM": "San Marino",
  "ST": "Sao Tome and Principe",
  "SA": "Saudi Arabia",
  "SN": "Senegal",
  "CS": "Serbia and Montenegro",
  "SC": "Seychelles",
  "SL": "Sierra Leone",
  "SG": "Singapore",
  "SK": "Slovakia",
  "SI": "Slovenia",
  "SB": "Solomon Islands",
  "SO": "Somalia",
  "ZA": "South Africa",
  "GS": "South Georgia and The South Sandwich Islands",
  "ES": "Spain",
  "LK": "Sri Lanka",
  "SD": "Sudan",
  "SR": "Suriname",
  "SJ": "Svalbard and Jan Mayen Islands",
  "SZ": "Swaziland",
  "SE": "Sweden",
  "CH": "Switzerland",
  "SY": "Syrian Arab Republic",
  "TW": "Taiwan",
  "TJ": "Tajikistan",
  "TZ": "Tanzania, United Republic of",
  "TH": "Thailand",
  "TL": "Timor-leste",
  "TG": "Togo",
  "TK": "Tokelau",
  "TO": "Tonga",
  "TT": "Trinidad and Tobago",
  "TN": "Tunisia",
  "TR": "Turkey",
  "TM": "Turkmenistan",
  "TC": "Turks and Caicos Islands",
  "TV": "Tuvalu",
  "UG": "Uganda",
  "UA": "Ukraine",
  "AE": "United Arab Emirates",
  "GB": "United Kingdom",
  "US": "United States",
  "UM": "United States Minor Outlying Islands",
  "UY": "Uruguay",
  "UZ": "Uzbekistan",
  "VU": "Vanuatu",
  "VA": "Vatican City State (holy See)",
  "VE": "Venezuela",
  "VN": "Viet Nam",
  "VG": "Virgin Islands (british)",
  "VI": "Virgin Islands (u.s.)",
  "WF": "Wallis and Futuna Islands",
  "EH": "Western Sahara",
  "YE": "Yemen",
  "ZM": "Zambia",
  "ZW": "Zimbabwe"
}